# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da1cef99836ecdfa5b09d073928a4e2bd99cf396f7a2e92e7054ac08990b5c976f28efb7379b64b2afd084e9d2c86bddf690e9e02e585f20e636dc0dcfef17b

test:
  secret_key_base: d16097b052d83ab3c5b3719e77aa832065e00e565a078af0dd93950fa8b76abd5e151e6e3ae20ca1f42615fd0cdb713264dab5f6027a0827881878201050cc2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
